version: 2
jobs:
  build:
    working_directory: ~/type-to-reducer
    docker:
      - image: circleci/node:10-jessie
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm run test -- --reporter spec
      - run: npm run build
